# Generated by Django 5.0.1 on 2024-01-30 16:36

import petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_created_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstagram.photos.models.validate_image_size]),
        ),
    ]
