# Generated by Django 5.0.1 on 2024-01-30 16:48

import petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[petstagram.photos.models.MaxFileSizeValidator(limit_value=1)]),
        ),
    ]
