# Generated by Django 5.0.1 on 2024-02-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0008_alter_petphoto_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoComents',
            new_name='PhotoComments',
        ),
    ]
